"""修改数据库结构。users：增加api_token字段;events增加repeat字段;增加admins表

Revision ID: 573a2cab6058
Revises: c4b965f2930d
Create Date: 2023-11-01 20:13:38.377511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573a2cab6058'
down_revision = 'c4b965f2930d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat', sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', name='repeattype'), nullable=False))
        batch_op.drop_constraint('events_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_constraint('reminders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['api_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_token')

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reminders_ibfk_1', 'events', ['event_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('events_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_column('repeat')

    # ### end Alembic commands ###
