"""修改reminder_type

Revision ID: 831c86966ec5
Revises: b336cd7abc63
Create Date: 2023-11-04 17:10:53.557936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '831c86966ec5'
down_revision = 'b336cd7abc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('reminder_type',
               existing_type=mysql.ENUM('NONE', 'EMAIL', 'PHONE', 'SMS', 'ROBOT'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('reminder_type',
               existing_type=mysql.ENUM('NONE', 'EMAIL', 'PHONE', 'SMS', 'ROBOT'),
               nullable=True)

    # ### end Alembic commands ###
