"""修改reminder_type

Revision ID: a16f791fecec
Revises: 831c86966ec5
Create Date: 2023-11-04 18:41:29.941299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a16f791fecec'
down_revision = '831c86966ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('reminder_type',
               existing_type=mysql.ENUM('NONE', 'EMAIL', 'PHONE', 'SMS', 'ROBOT'),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('reminder_type',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('NONE', 'EMAIL', 'PHONE', 'SMS', 'ROBOT'),
               existing_nullable=False)

    # ### end Alembic commands ###
