"""修改events,新增start_date,event_time,end_date,reminder_type.reminder_time,删除start_time,end_time;删除reminders表

Revision ID: b336cd7abc63
Revises: f9046e350895
Create Date: 2023-11-04 16:22:02.799942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b336cd7abc63'
down_revision = 'f9046e350895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('event_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('reminder_type', sa.Enum('NONE', 'EMAIL', 'PHONE', 'SMS', 'ROBOT', name='remindertype'), nullable=True))
        batch_op.add_column(sa.Column('reminder_time', sa.Float(), nullable=True))
        batch_op.alter_column('repeat',
               existing_type=mysql.ENUM('NONE', 'DAILY', 'WEEKLY', 'MONTHLY'),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('end_time', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('repeat',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('NONE', 'DAILY', 'WEEKLY', 'MONTHLY'),
               existing_nullable=False)
        batch_op.drop_column('reminder_time')
        batch_op.drop_column('reminder_type')
        batch_op.drop_column('end_date')
        batch_op.drop_column('event_time')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
