"""删除admin表，删除users表的api_token

Revision ID: faf37f44404c
Revises: 9f040ad018d0
Create Date: 2023-11-03 10:29:36.132035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'faf37f44404c'
down_revision = '9f040ad018d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.drop_index('api_token')
        batch_op.drop_column('api_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_index('api_token', ['api_token'], unique=False)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
